### PR TITLE
fix: dataset update did not parse dats strings

### PR DESCRIPTION
**Pull request by v-rocheleau**

### CODE REVIEW

**Review by davidlougheed — APPROVED** [review]
lgtm. are there tests for the DATS create/endpoint functions for both object-form DATS and stringified DATS?

**Comment by v-rocheleau** [comment]
> lgtm. are there tests for the DATS create/endpoint functions for both object-form DATS and stringified DATS?

The `/api/datasets/<id>/dats` endpoint only accepts GET requests.

**Comment by davidlougheed** [comment]
I meant the main dataset update/create points

**Comment by v-rocheleau** [comment]
Ah yeah I added tests on that one in the last dats PR

**Pull request merged**
