### PR TITLE
chore!: update to Django 5 and DRF 3.15

### PR DESCRIPTION
**Pull request by davidlougheed**
Note that this changed the behaviour of trying to create a duplicate project JSON schema (from 500 to 400). Is this acceptable?

### CODE REVIEW

**Review by v-rocheleau — APPROVED** [review]
Lgtm, the error code change should not impact bento_web, it will handle 400 or 500 as an error.
I did find out that there is a regression for project json-schema creation in bento_web, looking to fix it (not related to this PR).

**Comment by davidlougheed** [comment]
image

getting a strange error here (probably a breaking change to the remote user backend class with django), will investigate later

**Review by v-rocheleau — CHANGES_REQUESTED** [review]
Did my first test wrong, seems to break a number of requests. Investigating.

**Comment by davidlougheed** [comment]
@v-rocheleau pushed a fix to bento lib which makes katsu work (I think)

**Review by gsfk — APPROVED** [review]
Hammered as much as I could and didn't find anything specific to this pr. (For example, adding extra property schemas seems to be broken, but I assume this is the regression Victor is talking about above. The same bug is in the current release.)

**Pull request merged**
